plugins {
    id 'com.android.application'
}

android {
    namespace 'com.exel.watranslator'
    compileSdk 35

    defaultConfig {
        applicationId 'com.exel.watranslator'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.4-free-build'
    }
}

dependencies {
    implementation 'com.google.mlkit:translate:17.0.3'
}